"""
exporter.py – Export utilities for Literature Reviews to .docx and LaTeX (.tex).
"""
import re
import logging
from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

log = logging.getLogger(__name__)

def _clean_markdown(text: str) -> str:
    """Removes basic markdown markers for plain text insertion."""
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    return text

def _format_inline_docx(paragraph, text: str):
    """Parses basic markdown (bold, italic) and adds styled runs to a docx paragraph."""
    # Split text into segments of bold, italic, and normal text
    parts = re.split(r"(\*\*[^*]+\*\*|\*[^*]+\*)", text)
    for part in parts:
        if not part:
            continue
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        elif part.startswith("*") and part.endswith("*"):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        else:
            paragraph.add_run(part)

def export_to_docx(review, output_path) -> Path | None:
    """
    Exports a LiteratureReview object to a professionally styled Microsoft Word document.
    """
    doc = Document()
    
    # ── Page Setup ─────────────────────────────────────────────────────────────
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11.0)
    section.top_margin = Inches(1.0)
    section.bottom_margin = Inches(1.0)
    section.left_margin = Inches(1.0)
    section.right_margin = Inches(1.0)
    
    # ── Styling Palette ────────────────────────────────────────────────────────
    COLOR_PRIMARY   = RGBColor(31, 41, 55)   # #1F2937 (Slate Blue)
    COLOR_SECONDARY = RGBColor(75, 85, 99)   # #4B5563 (Muted Gray)
    COLOR_BODY      = RGBColor(55, 65, 81)   # #374151 (Dark Gray)
    
    # Configure styles
    style_normal = doc.styles['Normal']
    style_normal.font.name = 'Arial'
    style_normal.font.size = Pt(11)
    style_normal.font.color.rgb = COLOR_BODY
    style_normal.paragraph_format.line_spacing = 1.25
    style_normal.paragraph_format.space_after = Pt(8)
    
    # ── Document Title ─────────────────────────────────────────────────────────
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_p.paragraph_format.space_before = Pt(12)
    title_p.paragraph_format.space_after = Pt(4)
    run_title = title_p.add_run(f"Literature Review:\n{review.topic}")
    run_title.font.name = 'Arial'
    run_title.font.size = Pt(24)
    run_title.bold = True
    run_title.font.color.rgb = COLOR_PRIMARY
    
    # Subtitle / Format info
    sub_p = doc.add_paragraph()
    sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_p.paragraph_format.space_after = Pt(24)
    run_sub = sub_p.add_run(f"Citation Style: {review.citation_format}  |  Generated by arXiv Agent")
    run_sub.font.name = 'Arial'
    run_sub.font.size = Pt(9.5)
    run_sub.font.color.rgb = COLOR_SECONDARY
    run_sub.italic = True
    
    # ── Helpers for Headings ───────────────────────────────────────────────────
    def add_heading_1(text: str):
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(18)
        p.paragraph_format.space_after = Pt(6)
        p.paragraph_format.keep_with_next = True
        run = p.add_run(text)
        run.font.name = 'Arial'
        run.font.size = Pt(16)
        run.bold = True
        run.font.color.rgb = COLOR_PRIMARY
        return p

    # ── 1. Introduction ────────────────────────────────────────────────────────
    add_heading_1("1. Introduction")
    for para in review.introduction.split("\n\n"):
        if para.strip():
            p = doc.add_paragraph()
            _format_inline_docx(p, para.strip())
            
    # ── Theme Sections ─────────────────────────────────────────────────────────
    for idx, sec in enumerate(review.sections, 2):
        add_heading_1(f"{idx}. {sec.theme.title}")
        for para in sec.content.split("\n\n"):
            if para.strip():
                p = doc.add_paragraph()
                _format_inline_docx(p, para.strip())
                
    # ── Gaps, Future Work, Conclusion ──────────────────────────────────────────
    next_num = len(review.sections) + 2
    add_heading_1(f"{next_num}. Research Gaps and Open Problems")
    for para in review.gaps.split("\n\n"):
        if para.strip():
            p = doc.add_paragraph()
            _format_inline_docx(p, para.strip())
            
    add_heading_1(f"{next_num + 1}. Future Directions")
    for para in review.future_work.split("\n\n"):
        if para.strip():
            p = doc.add_paragraph()
            _format_inline_docx(p, para.strip())
            
    add_heading_1(f"{next_num + 2}. Conclusion")
    for para in review.conclusion.split("\n\n"):
        if para.strip():
            p = doc.add_paragraph()
            _format_inline_docx(p, para.strip())
            
    # ── References ─────────────────────────────────────────────────────────────
    if review.references:
        add_heading_1("References")
        from rag.agent.citation_formatter import CitationFormatter
        fmt = CitationFormatter(review.citation_format)
        ref_text = fmt.format_list(review.references)
        
        # Write references with hanging indent style
        for ref_line in ref_text.split("\n\n"):
            if ref_line.strip():
                p = doc.add_paragraph()
                p.paragraph_format.left_indent = Inches(0.35)
                p.paragraph_format.first_line_indent = Inches(-0.35)
                p.paragraph_format.space_after = Pt(6)
                _format_inline_docx(p, ref_line.strip())
                
    if isinstance(output_path, (str, Path)):
        doc.save(str(output_path))
        log.info("Saved review docx to %s", output_path)
        return Path(output_path)
    else:
        doc.save(output_path)
        log.info("Saved review docx to memory buffer")
        return None

def _markdown_to_latex(text: str) -> str:
    """Converts basic markdown bold/italic tags into standard LaTeX command equivalents."""
    # Escape standard LaTeX special symbols
    text = text.replace("\\", "\\backslash ")
    text = text.replace("&", "\\&")
    text = text.replace("%", "\\%")
    text = text.replace("$", "\\$")
    text = text.replace("#", "\\#")
    text = text.replace("_", "\\_")
    text = text.replace("{", "\\{")
    text = text.replace("}", "\\}")
    
    # Bold formatting
    text = re.sub(r"\*\*([^*]+)\*\*", r"\\textbf{\1}", text)
    # Italic formatting
    text = re.sub(r"\*([^*]+)\*", r"\\textit{\1}", text)
    # Inline code
    text = re.sub(r"`([^`]+)`", r"\\texttt{\1}", text)
    
    return text

def export_to_latex(review, output_path: str | Path) -> Path:
    """
    Exports a LiteratureReview object to an academic LaTeX (.tex) format.
    """
    from rag.agent.citation_formatter import CitationFormatter
    fmt = CitationFormatter(review.citation_format)
    
    # Clean topic for title
    title_clean = _markdown_to_latex(review.topic)
    
    latex_lines = [
        "\\documentclass[11pt,a4paper]{article}",
        "\\usepackage[utf8]{inputenc}",
        "\\usepackage{geometry}",
        "\\geometry{verbose,tmargin=1in,bmargin=1in,lmargin=1in,rmargin=1in}",
        "\\usepackage{hyperref}",
        "\\usepackage{booktabs}",
        "\\usepackage{microtype}",
        "\\usepackage{parskip}",
        "",
        f"\\title{{Literature Review:\\\\ \\textbf{{{title_clean}}}}}\\n",
        "\\author{\\textbf{arXiv Agent} \\\\ Automated Research Assistant}",
        f"\\date{{Generated: \\today \\\\ \\small Style: {review.citation_format}}}",
        "",
        "\\begin{document}",
        "\\maketitle",
        "\\hr",
        "",
        "\\section{Introduction}",
        _markdown_to_latex(review.introduction),
        ""
    ]
    
    for idx, sec in enumerate(review.sections, 2):
        latex_lines.append(f"\\section{{{_markdown_to_latex(sec.theme.title)}}}")
        latex_lines.append(_markdown_to_latex(sec.content))
        latex_lines.append("")
        
    latex_lines.append("\\section{Research Gaps and Open Problems}")
    latex_lines.append(_markdown_to_latex(review.gaps))
    latex_lines.append("")
    
    latex_lines.append("\\section{Future Directions}")
    latex_lines.append(_markdown_to_latex(review.future_work))
    latex_lines.append("")
    
    latex_lines.append("\\section{Conclusion}")
    latex_lines.append(_markdown_to_latex(review.conclusion))
    latex_lines.append("")
    
    if review.references:
        latex_lines.append("\\section*{References}")
        latex_lines.append("\\begin{description}")
        for idx, ref in enumerate(review.references, 1):
            ref_str = fmt._format_one(ref, idx)
            # Remove the citation key bracket prefix like [1] for description list item
            ref_str = re.sub(r"^\[\d+\]\s*", "", ref_str)
            latex_lines.append(f"  \\item[{review.citation_format.upper()} \\#{idx}] {_markdown_to_latex(ref_str)}")
        latex_lines.append("\\end{description}")
        
    latex_lines.append("\\end{document}")
    
    out_text = "\n".join(latex_lines)
    Path(output_path).write_text(out_text, encoding="utf-8")
    log.info("Saved review LaTeX to %s", output_path)
    return Path(output_path)
